### PR TITLE
Adding serviceFn

### PR DESCRIPTION
**Pull request by ragboyjr**
- Added new serviceFn function to create service functions
  instead of classes
- Refactored service into serviceFactory to share code between
  serviceFn and service.

Signed-off-by: RJ Garcia <rj@bighead.net>

### CODE REVIEW

**Comment by ragboyjr** [comment]
This could resolve #103

**Comment by young-steveo** [comment]
Thanks for the PR!

I think I can be convinced that an "injectable factory" method like `serviceFn` is a good addition, but I would make a couple of suggestions for this PR:

- The main difference between this new function and the `bottle.factory` is that this factory will be injected with dependencies as arguments to the factory instead of having the entire container injected.  I think this should be explained in the Readme (as it stands it could be confused that  `bottle.serviceFn` is exactly like `bottle.factory`)
- Don't expose `serviceFactory` internals to the public api.  You can leave the `bottle.service` tests where they were, unchanged, and write some new tests for the `serviceFn` to show how it's different.
- I'm not keen on the abbreviated `serviceFn` name; none of the other bottle api methods use abbreviations, so it makes this one stand out.  You could maybe rename it to `serviceFactory`, and then rename your internal `serviceFactory` to something else.  This will align well with the current `instanceFactory` method name.

**Comment by ragboyjr** [comment]
Awesome, will do, all of your points sound good. thanks for taking the time to review!

**Comment by ragboyjr** [comment]
@young-steveo updated.

**Pull request merged**
