### PR TITLE
feature: optimize `.service`

### PR DESCRIPTION
**Pull request by nswbmw**
for less code

### CODE REVIEW

**Comment by young-steveo** [comment]
@nswbmw Thanks for the PR.

I'm disinclined to derive service dependencies from the function signature at runtime since minification will break the implementation.  Angular's automatic injector service deals with this by introducing the "array form" of the injection syntax (of which I'm not a fan), which is slightly more bulky than bottle's current behavior of passing strings.

**Comment by nswbmw** [comment]
Thanks for your reply.

In angular, both writing are ok:

```
myApp.service('myService', ['API', function(API) {
  ...
}]);

myApp.service('myService', function(API) {
  ...
});
```

In bottlejs, i think both should be ok:

```
b.service('myService', function(myService) {
  ...
}, 'myService');

b.service('myService', function(myService) {
  ...
});
```

No breaking change, and it inject services from the function signature before actual call this service, right?

**Comment by young-steveo** [comment]
This version:

```js
b.service('myService', function(someDependency) { });
```
Will get minified to:

```js
b.service('myService', function(a) { });
```
That will break the injection, since the `fnArgs` method will return `'a'` instead of `'someDependency'`.  That's a pretty big "gotcha" that will lead to developers either reporting false bugs, or forcing them to use the current, longer syntax anyway.

I'd rather avoid adding a feature to bottle that won't work when the userland code is minified.  However, I do like fact that less code has to be written.  If you can fathom a way to do it where it doesn't break, I'd be all ears.

**Comment by nswbmw** [comment]
understand :)

**Pull request closed without merging**
